version: "2"

services:
  test:
    image: xibitdigital/nginx-ssl-mod-security
    volumes:
      - "./index.html:/usr/share/nginx/html/index.html"
      - "./test.conf:/etc/nginx/conf.d/test.conf"
    ports:
      - "80:80"
